#define ASPECT_RATIO (16.0 / 9.0)
#define OUTPUT_WIDTH 2048
#define RENDER_RESOLUTION 1 /* ]0,1] */
#define SAMPLES_PER_PIXEL 4
#define VIEWPOINT_DIST 1

#define RAY_RECUSION_LIMIT 4
#define AMBIENT_LIGHT_INTENSITY 0.08

#define CAN_PROJ_ORTO 0
